"""Boltz-2 structure and affinity prediction through its native YAML input."""

from __future__ import annotations

import os
import re
import tarfile
import tempfile
from pathlib import Path
from typing import Any

import yaml

from . import (
    ToolExecutionError,
    ToolInputError,
    ToolUnavailable,
    catalog_spec,
    readable_files,
    run_command,
    text,
    tool_fields,
    tool_script,
    torch_device,
)
from .environments import environment_path, environment_python
from .field_processing import (
    boolean,
    decimal,
    document_input,
    integer,
    json_list,
    molecule_boxes,
    safe_name,
)
from .status_check import CheckResult, ToolStatus, probe_cli

SPEC = catalog_spec("boltz2", fields=tool_fields("boltz2"))


def has_cuequivariance_kernels() -> bool:
    """Whether Boltz's environment has the cuEquivariance kernels it uses by default.

    They come from the `boltz[cuda]` extra, whose wheels are Linux-only; bio_tools
    installs plain Boltz elsewhere, or when the extra does not resolve. Boltz does
    not fall back on its own: without them, the first triangle update raises
    `ModuleNotFoundError: cuequivariance_torch`. Checked on disk rather than by
    launching the environment's interpreter.
    """

    root = environment_path("boltz")
    if os.name == "nt":
        site_packages = [root / "Lib" / "site-packages"]
    else:
        site_packages = list(root.glob("lib/python*/site-packages"))
    return any((path / "cuequivariance_torch").is_dir() for path in site_packages)


def from_boxes(payload: dict[str, Any]) -> str:
    """The molecule boxes as Boltz YAML, for "Set parameters here"."""

    boxes = molecule_boxes(payload, allow_ids=True, require_ids=True)
    sequences: list[dict[str, Any]] = []
    for box in boxes:
        native_id: str | list[str] = box.ids[0] if len(box.ids) == 1 else box.ids
        if box.kind == "ligand":
            # A CCD_ code names a component from the dictionary; anything else
            # is read as SMILES, which is how the other adapters take it too.
            entity: dict[str, Any] = {"id": native_id}
            if box.ligand.upper().startswith("CCD_"):
                entity["ccd"] = box.ligand[4:].upper()
            else:
                entity["smiles"] = box.ligand
            sequences.append({"ligand": entity})
            continue
        entity = {"id": native_id, "sequence": box.sequence}
        if box.cyclic:
            entity["cyclic"] = True
        if box.modifications:
            entity["modifications"] = [
                {"position": mod.position, "ccd": mod.residue}
                for mod in box.modifications
            ]
        # Without an alignment Boltz wants to be told so explicitly, unless the
        # run is opting into the public MSA server below.
        if box.kind == "protein":
            if box.msa not in (None, ""):
                if not isinstance(box.msa, str):
                    raise ToolInputError(
                        f'Molecule "{box.chain}" MSA must be a path or "empty".'
                    )
                entity["msa"] = box.msa.strip()
            elif not boolean(payload, "use_msa_server", True):
                entity["msa"] = "empty"
        sequences.append({box.kind: entity})

    document: dict[str, Any] = {"version": 1, "sequences": sequences}
    for field in ("constraints", "templates", "properties"):
        values = json_list(payload, field, max_length=500_000)
        if values:
            document[field] = values
    return yaml.safe_dump(
        document,
        sort_keys=False,
        default_flow_style=False,
        width=1_000_000,
    )


def check_msas(yaml_input: str, use_msa_server: bool) -> None:
    """Refuse the MSA combinations Boltz rejects, before it loads the model.

    Boltz reads a protein's `msa` as a path (supplied), `empty` (single
    sequence), or absent (generated by the server). It cannot mix supplied and
    generated MSAs in one input, and it needs the server for any absent one.
    A document that does not parse is left for Boltz to report.
    """

    try:
        document = yaml.safe_load(yaml_input)
    except yaml.YAMLError:
        return
    if not isinstance(document, dict) or not isinstance(document.get("sequences"), list):
        return

    supplied: list[str] = []
    generated: list[str] = []
    for entry in document["sequences"]:
        entity = entry.get("protein") if isinstance(entry, dict) else None
        if not isinstance(entity, dict):
            continue
        name = str(entity.get("id", "?"))
        msa = entity.get("msa")
        if msa in (None, ""):
            generated.append(name)
        elif msa != "empty":
            supplied.append(name)

    if generated and not use_msa_server:
        raise ToolInputError(
            f"Protein {', '.join(generated)} has no MSA. Turn on the MSA server, "
            "give an MSA path, or set msa: empty for single-sequence mode."
        )
    if generated and supplied:
        raise ToolInputError(
            "Boltz cannot mix supplied and server-generated MSAs in one input: "
            f"protein {', '.join(supplied)} has an MSA path, but "
            f"{', '.join(generated)} does not. Give those a path too, or set "
            "msa: empty on them."
        )


def run(payload: dict[str, Any]) -> dict[str, Any]:
    name = safe_name(payload, default="boltz2-demo")
    payload = document_input(
        payload, "yaml_spec", from_boxes=from_boxes, max_length=500_000
    )
    yaml_input = text(payload, "yaml_spec", max_length=500_000)

    recycling_steps = integer(
        payload, "recycling_steps", default=3, minimum=1, maximum=20
    )
    sampling_steps = integer(
        payload, "sampling_steps", default=200, minimum=10, maximum=1_000
    )
    diffusion_samples = integer(
        payload, "diffusion_samples", default=1, minimum=1, maximum=50
    )
    step_scale = decimal(payload, "step_scale", default=1.5, minimum=0, maximum=5)
    sampling_steps_affinity = integer(
        payload, "sampling_steps_affinity", default=200, minimum=1, maximum=1_000
    )
    diffusion_samples_affinity = integer(
        payload, "diffusion_samples_affinity", default=5, minimum=1, maximum=50
    )
    seed = integer(payload, "seed", default=0, minimum=0, maximum=4_294_967_295)
    output_format = str(payload.get("output_format") or "mmcif")
    if output_format not in {"mmcif", "pdb"}:
        raise ToolInputError(f"Unsupported output_format: {output_format}.")
    use_msa_server = boolean(payload, "use_msa_server", True)
    msa_server_url = str(
        payload.get("msa_server_url") or "https://api.colabfold.com"
    ).strip()
    if not re.fullmatch(r"https://[^\s]+", msa_server_url):
        raise ToolInputError("msa_server_url must be an HTTPS URL.")
    check_msas(yaml_input, use_msa_server)

    command = [
        tool_script("boltz", "boltz", "BOLTZ_EXECUTABLE"),
        "predict",
        "input.yaml",
        "--model",
        "boltz2",
        "--out_dir",
        name,
        "--recycling_steps",
        str(recycling_steps),
        "--sampling_steps",
        str(sampling_steps),
        "--diffusion_samples",
        str(diffusion_samples),
        "--step_scale",
        str(step_scale),
        "--sampling_steps_affinity",
        str(sampling_steps_affinity),
        "--diffusion_samples_affinity",
        str(diffusion_samples_affinity),
        "--seed",
        str(seed),
        "--output_format",
        output_format,
    ]
    if use_msa_server:
        command += ["--use_msa_server", "--msa_server_url", msa_server_url]
    if boolean(payload, "use_potentials"):
        command.append("--use_potentials")
    if boolean(payload, "affinity_mw_correction"):
        command.append("--affinity_mw_correction")
    if not has_cuequivariance_kernels():
        command.append("--no_kernels")

    with tempfile.TemporaryDirectory(prefix="bio-web-boltz2-") as temporary:
        workdir = Path(temporary)
        input_path = workdir / "input.yaml"
        output_path = workdir / name
        input_path.write_text(yaml_input, encoding="utf-8")
        result = run_command(
            command,
            cwd=workdir,
            artifacts=[output_path, input_path],
        )
        generated = readable_files(output_path)
        extension = "cif" if output_format == "mmcif" else "pdb"
        structures = list(output_path.glob(f"boltz_results_*/predictions/*/*.{extension}"))
        msa_reply = _msa_server_reply(output_path) if use_msa_server else ""

    # `boltz predict` catches a failure while preparing an input, prints
    # "Failed to process ... Skipping." and exits 0 with nothing predicted, so
    # a run that did nothing is only visible from what it left behind.
    if not structures:
        if msa_reply:
            raise ToolExecutionError(
                f"The MSA server ({msa_server_url}) replied with an error instead of "
                f"an alignment: {msa_reply} Public ColabFold server errors are "
                "usually temporary; run again, or supply MSAs yourself."
            )
        raise ToolExecutionError(
            "Boltz exited without writing a structure. "
            + (_failure_detail(result.get("stdout") or "") or "See the run log for details.")
        )

    return {
        "status": "completed",
        "input": {"yaml": yaml_input},
        "generated_files": generated,
        **result,
    }


def _msa_server_reply(output: Path) -> str:
    """The server's reply, when Boltz saved one in place of an MSA download.

    Boltz writes the body of `result/download` to `out.tar.gz` without checking
    the HTTP status, so an error from the server (e.g. a 404 JSON body) becomes
    a "not a gzip file" failure that hides what the server said.
    """

    for archive in sorted(output.glob("boltz_results_*/msa/*/out.tar.gz")):
        if tarfile.is_tarfile(archive):
            continue
        reply = archive.read_bytes()[:1_000].decode("utf-8", errors="replace").strip()
        return reply or "an empty response."
    return ""


def _failure_detail(stdout: str) -> str:
    """Boltz's error for an input it skipped, with its continuation lines."""

    lines = stdout.splitlines()
    for index, line in enumerate(lines):
        if line.startswith("Failed to process ") and " Error: " in line:
            detail = [line.split(" Error: ", 1)[1]]
            for following in lines[index + 1 :]:
                if not following.startswith("- "):
                    break
                detail.append(following)
            message = "\n".join(detail).strip()
            return message if len(message) <= 2_000 else message[:2_000] + "…"
    return ""


def check_status() -> ToolStatus:
    try:
        boltz = tool_script("boltz", "boltz", "BOLTZ_EXECUTABLE")
    except ToolUnavailable as exc:
        return ToolStatus(CheckResult.NOT_INSTALLED, str(exc))
    status = probe_cli([boltz])
    if status.result == CheckResult.PASS:
        status.device = torch_device(environment_python("boltz"))
    return status
