//! Form contracts, one file per tool.

/// Serialized field and task definitions for a tool catalog entry.
pub fn by_slug(slug: &str) -> Option<&'static str> {
    match slug {
        "abmpnn" => Some(include_str!("abmpnn.json")),
        "aggrescan3d" => Some(include_str!("aggrescan3d.json")),
        "alphafold3" => Some(include_str!("alphafold3.json")),
        "antibody_annotator" => Some(include_str!("antibody_annotator.json")),
        "antifold" => Some(include_str!("antifold.json")),
        "bindcraft" => Some(include_str!("bindcraft.json")),
        "biophi" => Some(include_str!("biophi.json")),
        "boltz2" => Some(include_str!("boltz2.json")),
        "boltz_adme" => Some(include_str!("boltz_adme.json")),
        "boltzgen" => Some(include_str!("boltzgen.json")),
        "catpred" => Some(include_str!("catpred.json")),
        "chai1" => Some(include_str!("chai1.json")),
        "deepimmuno" => Some(include_str!("deepimmuno.json")),
        "deepsp" => Some(include_str!("deepsp.json")),
        "deepstabp" => Some(include_str!("deepstabp.json")),
        "dlkcat" => Some(include_str!("dlkcat.json")),
        "esmfold2" => Some(include_str!("esmfold2.json")),
        "enzymemap" => Some(include_str!("enzymemap.json")),
        "genie3" => Some(include_str!("genie3.json")),
        "germinal" => Some(include_str!("germinal.json")),
        "gromacs" => Some(include_str!("gromacs.json")),
        "highfold" => Some(include_str!("highfold.json")),
        "igblast" => Some(include_str!("igblast.json")),
        "igdesign" => Some(include_str!("igdesign.json")),
        "immunebuilder" => Some(include_str!("immunebuilder.json")),
        "ligandmpnn" => Some(include_str!("ligandmpnn.json")),
        "mber" => Some(include_str!("mber.json")),
        "netsolp" => Some(include_str!("netsolp.json")),
        "opendde" => Some(include_str!("opendde.json")),
        "orca" => Some(include_str!("orca.json")),
        "pdbbind" => Some(include_str!("pdbbind.json")),
        "placer" => Some(include_str!("placer.json")),
        "proteinmpnn" => Some(include_str!("proteinmpnn.json")),
        "proteinmpnn_ddg" => Some(include_str!("proteinmpnn_ddg.json")),
        "protenix" => Some(include_str!("protenix.json")),
        "rdkit" => Some(include_str!("rdkit.json")),
        "rfantibody" => Some(include_str!("rfantibody.json")),
        "rfdiffusion" => Some(include_str!("rfdiffusion.json")),
        "retrobiocat" => Some(include_str!("retrobiocat.json")),
        "tap" => Some(include_str!("tap.json")),
        "thermompnn" => Some(include_str!("thermompnn.json")),
        "tlimmuno" => Some(include_str!("tlimmuno.json")),
        _ => None,
    }
}
