//! A descriptor of parsing stdout output from a program. Note: We don't handle outputs
//! symmetrically for this at this point, as their structure is more diverse.
//!
//! this module may also handle files generated by an tool, vs parsing stdout.

